### ISSUE TITLE
Question regarding deploying a new .pbix

### ISSUE THREAD

**Issue by dw1186** [nathangiusti/Power-BI-Pipeline-Deploy#5]
I can only get this to work if the .pbix already exists in the target workspace.  When I deploy a brand new .pbix from DEV to TEST it throws an error unless the .pbix already exists in the target workspace.

**Comment by nathangiusti** [comment]
Set source_stage_order to 0


    name: Migrate via Pipeline
    on:
      push:
        branches:
          - main
    jobs:
      Deploy-Asset:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Get changed files
            id: changed-files
            uses: tj-actions/changed-files@v12
            with:
              separator: ","
              quotepath: false
          - name: Power BI Pipeline Deploy
            uses: nathangiusti/Power-BI-Pipeline-Deploy@v2.4
            with:
              files: ${{ steps.changed-files.outputs.all_modified_files }}
              separator: ","
              tenant_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              config_file: ".github/config/pipeline-deploy-config.yaml"
              source_stage_order: 0
            env:
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

**Comment by dw1186** [comment]
Thanks for responding.

Below is my code which already has the source_stage_order set to 0.  I must have something else wrong.  I’ve included the log with the error highlighted in yellow at the end of this email.  Any help would be greatly appreciated.  Thanks!

name: CI

# only run when files in the root of the main branch are committed and ignore changes in the sub-directories.
on:
  push:
    branches:
      - main
jobs:
  DeployToUAT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: EideBaillyWidgets.DeployUAT
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ***@***.***
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: ***@***.***
        with:
          separator: ","
          quotepath: false
      - name: Power BI Pipeline Deploy
        uses: ***@***.***
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
          tenant_id: " xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx " (I removed this)
          config_file: ".github/workflows/config.yaml"
          source_stage_order: 0
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}



Run ***@***.******@***.***>
2<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:2> with:
3<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:3> files: Workspace_Reports/Eide Bailly Widgets SemiAnnual Sales.pbix
4<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:4> separator: ,
5<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:5> tenant_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   (I removed this)
6<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:6> config_file: .github/workflows/config.yaml
7<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:7> source_stage_order: 0
8<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:8> update_app_in_target_workspace: false
9<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:9> allow_purge_data: false
10<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:10> env:
11<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:11> CLIENT_ID: ***
12<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:12> CLIENT_SECRET: ***
13<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:14>/usr/bin/docker run --name d5581fe99acba552c4fb9b7134354806c1c65_5cf345 --label 8d5581 --workdir /github/workspace --rm -e "CLIENT_ID" -e "CLIENT_SECRET" -e "INPUT_FILES" -e "INPUT_SEPARATOR" -e "INPUT_TENANT_ID" -e "INPUT_CONFIG_FILE" -e "INPUT_SOURCE_STAGE_ORDER" -e "INPUT_UPDATE_APP_IN_TARGET_WORKSPACE" -e "INPUT_ALLOW_PURGE_DATA" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/PowerBI-EideBaillyWidgets/PowerBI-EideBaillyWidgets":"/github/workspace" 8d5581:fe99acba552c4fb9b7134354806c1c65 "Workspace_Reports/Eide Bailly Widgets SemiAnnual Sales.pbix" "," "220568a8-fd7d-48a1-978a-0fff06c0bc35" "0" "false" "false" ".github/workflows/config.yaml"
14<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:15>WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
15<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:16>Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (22.0.4)
16<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:17>Collecting pip
17<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:18> Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
18<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:19> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 37.9 MB/s eta 0:00:00
19<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:20>Installing collected packages: pip
20<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:21> Attempting uninstall: pip
21<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:22> Found existing installation: pip 22.0.4
22<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:23> Uninstalling pip-22.0.4:
23<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:24> Successfully uninstalled pip-22.0.4
24<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:25>Successfully installed pip-22.2.2
25<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:26>WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
26<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:27>WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
27<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:28>Collecting requests
28<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:29> Downloading requests-2.28.1-py3-none-any.whl (62 kB)
29<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:30> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.2 MB/s eta 0:00:00
30<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:31>Collecting charset-normalizer<3,>=2
31<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:32> Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
32<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:33>Collecting certifi>=2017.4.17
33<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:34> Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
34<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:35> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 24.6 MB/s eta 0:00:00
35<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:36>Collecting urllib3<1.27,>=1.21.1
36<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:37> Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
37<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:38> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 109.5 MB/s eta 0:00:00
38<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:39>Collecting idna<4,>=2.5
39<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:40> Downloading idna-3.4-py3-none-any.whl (61 kB)
40<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:41> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 134.5 MB/s eta 0:00:00
41<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:42>Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
42<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:43>WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
43<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:44>Successfully installed certifi-2022.9.24 charset-normalizer-2.1.1 idna-3.4 requests-2.28.1 urllib3-1.26.12
44<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:45>WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
45<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:46>Collecting pyyaml
46<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:47> Downloading PyYAML-6.0.tar.gz (124 kB)
47<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:48> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 10.5 MB/s eta 0:00:00
48<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:49> Installing build dependencies: started
49<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:50> Installing build dependencies: finished with status 'done'
50<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:51> Getting requirements to build wheel: started
51<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:52> Getting requirements to build wheel: finished with status 'done'
52<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:53> Preparing metadata (pyproject.toml): started
53<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:54> Preparing metadata (pyproject.toml): finished with status 'done'
54<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:55>Building wheels for collected packages: pyyaml
55<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:56> Building wheel for pyyaml (pyproject.toml): started
56<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:57> Building wheel for pyyaml (pyproject.toml): finished with status 'done'
57<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:58> Created wheel for pyyaml: filename=PyYAML-6.0-cp39-cp39-linux_x86_64.whl size=45331 sha256=82d79e84293edc15bb1fbc2991a401d622321d9b509d78af978371ee2920b374
58<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:59> Stored in directory: /tmp/pip-ephem-wheel-cache-vet8zl_g/wheels/b4/0f/9a/d6af48581dda678920fccfb734f5d9f827c6ed5b4074c7eda8
59<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:60>Successfully built pyyaml
60<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:61>Installing collected packages: pyyaml
61<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:62>WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
62<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:63>Successfully installed pyyaml-6.0
63<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:64>Traceback (most recent call last):
64<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:65> File "/scripts/pipeline_deploy.py", line 109, in <module>
65<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:66> main()
66<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:67> File "/scripts/pipeline_deploy.py", line 104, in main
67<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:68> parse_response(response)
68<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:69> File "/scripts/pipeline_deploy.py", line 11, in parse_response
69<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:70> raise Exception(
70<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:71>Exception: ERROR: 400: b'{"error":{"code":"Alm_InvalidRequest_ArtifactsValidationFailure","pbi.error":{"code":"Alm_InvalidRequest_ArtifactsValidationFailure","details":[{"code":"Alm_InvalidRequest_MissingTargetReferencedDataset","detail":{"type":1,"value":"{\\"artifactTypeName\\":\\"Reports\\",\\"artifactId\\":\\"638909ae-4716-4a9d-b86b-863d15189e65\\"}"}}],"exceptionCulprit":1}}}'
71<https://github.com/EideBailly/PowerBI-EideBaillyWidgets/actions/runs/3206355660/jobs/5240007763#step:5:72>URL: https://api.powerbi.com/v1.0/myorg/pipelines/10acc45e-cfe5-45bf-807d-6afba1023541/deploy
Post Run ***@***.***
0s
Complete job
0s


Dave Winkels
Director of Business Intelligence and Analytics
Fargo, ND

T     701.476.8426

Access your documents with Eide Bailly Connect<https://www.eidebailly.com/client-access>

***@***.***<http://www.linkedin.com/companies/eide-bailly-llp>
***@***.***<https://twitter.com/EideBaillyLLP>
***@***.***<https://www.youtube.com/user/eidebailly>
***@***.***<https://www.facebook.com/EideBailly>
***@***.***<https://instagram.com/eidebailly/>

**Comment by nathangiusti** [comment]
@dw1186 Are you attempting to move PBIX reports with embedded datasets? As in the dataset is held within the PBIX file?

**Comment by dw1186** [comment]
Yes


Dave Winkels

Director of Business Intelligence & Analytics

Eide Bailly LLP

3203 32nd Ave S.

Fargo, ND 58103-6242



T     701.476.8426<tel:+17014768426>

C     701.361.0733<tel:+17013610733>

F     701.476.8998<tel:+17014768998>



Access your documents with Eide Bailly Connect<https://www.eidebailly.com/client-access>



What inspires you, inspires us.

eidebailly.com<https://www.eidebailly.com/>


________________________________

**Comment by dw1186** [comment]
Everything works fine when the .pbix already exists in the target workspace.  It only errors out when a new report is being deployed to a workspace where it does not already exist.

Dave Winkels
Director of Business Intelligence and Analytics
Fargo, ND

T     701.476.8426

Access your documents with Eide Bailly Connect<https://www.eidebailly.com/client-access>

***@***.***<http://www.linkedin.com/companies/eide-bailly-llp>
***@***.***<https://twitter.com/EideBaillyLLP>
***@***.***<https://www.youtube.com/user/eidebailly>
***@***.***<https://www.facebook.com/EideBailly>
***@***.***<https://instagram.com/eidebailly/>


________________________________

Confidentiality Note: This email message, including any attachment(s), is for the sole use of the intended recipient(s) and may contain information that is confidential, privileged, or otherwise protected by law. Any unauthorized use, disclosure, or distribution of this communication is strictly prohibited. If you have received this communication in error, please contact the sender immediately by reply email and destroy the original and all copies of the email, including any attachment(s).

**Comment by nathangiusti** [comment]
@dw1186 

I believe the issue is due to the PBIX files containing the dataset. Our current use case separates datasets from reports. I will need to make some updates to handle this.

**Comment by dw1186** [comment]
Thank you for looking into this.  For a new Power BI dashboard, what would the appropriate steps be to deploy using your action?  Would I have to manually deploy the dataset prior to running your action?  Thanks again.

Dave Winkels
Director of Business Intelligence and Analytics
Fargo, ND

T     701.476.8426

Access your documents with Eide Bailly Connect<https://www.eidebailly.com/client-access>

***@***.***<http://www.linkedin.com/companies/eide-bailly-llp>
***@***.***<https://twitter.com/EideBaillyLLP>
***@***.***<https://www.youtube.com/user/eidebailly>
***@***.***<https://www.facebook.com/EideBailly>
***@***.***<https://instagram.com/eidebailly/>

**Comment by nathangiusti** [comment]
Yes unfortunately. I will look into supporting this.

**Comment by nathangiusti** [comment]
See new release v2.5
